name: build_stable (KSU)

on:

  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        device: [m21, m31]
        old: [0, 1]
        ksu: [1]
    name: "🚧 Build for ${{matrix.device}} KSU=${{matrix.ksu}} OLD=${{matrix.old}}"

    steps:
      - name: Checkout source
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - uses: szenius/set-timezone@v1.0
        with:
          timezoneLinux: "Asia/Kolkata"

      - name: Setup Toolchains
        run: |
          sudo apt update
          sudo apt install python3 python-is-python3 -y
          mkdir -p toolchain
          cd toolchain
          ../download XSans0/WeebX-Clang WeebX-Clang-18.1.7-release WeebX-Clang-18.1.7.tar.gz
          tar -xvf WeebX-Clang*.tar.gz
          rm -rf WeebX-Clang*.tar.gz

      - name: Run build
        run: |

          DEVICE=${{matrix.device}} KSU=${{matrix.ksu}} OLD=${{matrix.old}} ./build.sh

      - name: Upload to Telegram
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_CHAT_ID }}
          token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          document: AnyKernel3/N*.zip

      - name: Upload kernel
        uses: actions/upload-artifact@v4
        with:
          name: N_kernel-${{matrix.device}}_Clang_18
          path: AnyKernel3/N*.zip
